# Generated by Django 5.2.4 on 2025-07-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='password',
            field=models.CharField(default=44, max_length=128),
            preserve_default=False,
        ),
    ]
